name: Schedule Test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule 실행 확인
        run: |
          echo "SCHEDULE TEST"
          date -u
